const Remarkable = require('remarkable');
const { JS } = require('fsts');
const toSlug = require('./components/toSlug.js');

const TABLE_OF_CONTENTS_TOKEN = '<AUTOGENERATED_TABLE_OF_CONTENTS>';

const linkIcon = '<svg aria-hidden="true" height="16" version="1.1" viewBox="0 0 16 16" width="16"><path fill-rule="evenodd" d="M4 9h1v1H4c-1.5 0-3-1.69-3-3.5S2.55 3 4 3h4c1.45 0 3 1.69 3 3.5 0 1.41-.91 2.72-2 3.25V8.59c.58-.45 1-1.27 1-2.09C10 5.22 8.98 4 8 4H4c-.98 0-2 1.22-2 2.5S3 9 4 9zm9-3h-1v1h1c1 0 2 1.22 2 2.5S13.98 12 13 12H9c-.98 0-2-1.22-2-2.5 0-.83.42-1.64 1-2.09V6.25c-1.09.53-2 1.84-2 3.25C6 11.31 7.55 13 9 13h4c1.45 0 3-1.69 3-3.5S14.5 6 13 6z"></path></svg>'

const encodeHtml = content => {
  return content.replace(/</g, '&lt;')
    .replace(/>/g, '&gt;');
}

class Parser {
  constructor(site) {
    this.site = site;

    this.style = this.style.bind(this);
    this.heading = this.heading.bind(this);
    this.paragraph = this.paragraph.bind(this);
    this.list = this.list.bind(this);
    this.code = this.code.bind(this);
    this.fence = this.fence.bind(this);
    this.table = this.table.bind(this);

    this.md = new Remarkable('full', {
      html: true,
      linkify: true,
    });
    this.md.use(this.heading);
    this.md.use(this.paragraph);
    this.md.use(this.list);
    this.md.use(this.code);
    this.md.use(this.fence);
    this.md.use(this.table);
  }

  style(theme, cls) {
    const style = theme[cls];
    const css = JS.styleToCss(style);
    return css.length > 1? css.substr(1, css.length - 2) : css;
  }

  /**
   * Adds GFM-style anchors to headings.
   */
  heading(md) {
    const that = this;
    md.renderer.rules.heading_open = function(tokens, idx, options, env) {
      const level = tokens[idx].hLevel;
      const theme = that.site.theme.md;
      const css = that.style(theme, 'h' + level);
      const anchorCss = that.style(theme, 'anchor');

      const content = tokens[idx + 1].content;
      const slug = toSlug(content);
      return (
        '<h' + level + ' style="' + css + '">' +
        '<a name="' + slug + '" aria-hidden="true" style="' + anchorCss + '"></a>' +
        '<a href="#' + slug + '" aria-hidden="true" class="hash-link" >' + linkIcon + '</a>'
      );
    };
    md.renderer.rules.heading_close = function(tokens, idx, options, env) {
      const level = tokens[idx].hLevel;
      return '</h' + level + '>';
    }
  }

  paragraph(md) {
    const that = this;
    md.renderer.rules.paragraph_open = function(tokens, idx, options, env) {
      const theme = that.site.theme.md;
      const css = that.style(theme, 'p');
      const cssLiP = that.style(theme, 'li_p');
      const insideLi = idx > 0 && tokens[idx - 1].type === 'list_item_open';
      return insideLi
        ? '<p style="' + cssLiP + '">'
        : '<p style="' + css + '">';
    };
    md.renderer.rules.paragraph_close = function(tokens, idx, options, env) {
      return '</p>';
    }
  }

  list(md) {
    const that = this;
    md.renderer.rules.bullet_list_open = function(tokens, idx, options, env) {
      const theme = that.site.theme.md;
      const cssUl = that.style(theme, 'ul');
      return '<ul style="' + cssUl + '">';
    }
    md.renderer.rules.bullet_list_close = function(tokens, idx, options, env) {
      return '</ul>';
    }
    md.renderer.rules.ordered_list_open = function(tokens, idx, options, env) {
      const theme = that.site.theme.md;
      const cssOl = that.style(theme, 'ol');
      return '<ol style="' + cssOl + '">';
    }
    md.renderer.rules.ordered_list_close = function(tokens, idx, options, env) {
      return '</ol>';
    }
  }

  code(md) {
    const that = this;
    md.renderer.rules.code = function(tokens, idx, options, env) {
      const theme = that.site.theme.md;
      const css = that.style(theme, 'code');
      return '<code style="' + css + '">' + tokens[idx].content + '</code>';
    }
  }

  fence(md) {
    const that = this;
    md.renderer.rules.fence = function(tokens, idx, options, env) {
      const theme = that.site.theme.md;
      const css = that.style(theme, 'fence');
      const token = tokens[idx];
      let cssFence = css;
      if (token.params) {
        const style_name = 'fence_' + token.params;
        if (theme[style_name]) { cssFence = that.style(theme, style_name); }
      }
      return '<pre><code style="' + cssFence + '">' +
        encodeHtml(tokens[idx].content) +
        '</code></pre>';
    };
  };

  table(md) {
    const that = this;
    md.renderer.rules.table_open = function(tokens, idx, options, env) {
      const theme = that.site.theme.md;
      const css = that.style(theme, 'table');
      return '<table style="' + css + '">';
    };
    md.renderer.rules.table_close = function(tokens, idx, options, env) {
      return '</table>';
    };
    md.renderer.rules.thead_open = function(tokens, idx, options, env) {
      const theme = that.site.theme.md;
      const css = that.style(theme, 'thead');
      return '<thead style="' + css + '">';
    };
    md.renderer.rules.thead_close = function(tokens, idx, options, env) {
      return '</thead>';
    };
    md.renderer.rules.tbody_open = function(tokens, idx, options, env) {
      const theme = that.site.theme.md;
      const css = that.style(theme, 'tbody');
      return '<tbody style="' + css + '">';
    };
    md.renderer.rules.tbody_close = function(tokens, idx, options, env) {
      return '</tbody>';
    };
    md.renderer.rules.tr_open = function(tokens, idx, options, env) {
      const theme = that.site.theme.md;
      const css = that.style(theme, 'tr');
      return '<tr style="' + css + '">';
    };
    md.renderer.rules.tr_close = function(tokens, idx, options, env) {
      return '</tr>';
    };
    md.renderer.rules.th_open = function(tokens, idx, options, env) {
      const theme = that.site.theme.md;
      const css = that.style(theme, 'th');
      return '<th style="' + css + '">';
    };
    md.renderer.rules.th_close = function(tokens, idx, options, env) {
      return '</th>';
    };
    md.renderer.rules.td_open = function(tokens, idx, options, env) {
      const theme = that.site.theme.md;
      const css = that.style(theme, 'td');
      return '<td style="' + css + '">';
    };
    md.renderer.rules.td_close = function(tokens, idx, options, env) {
      return '</td>';
    };
  };

  headings(content) {
    const rx = /^(#{1,3})\s+(.*)/;
    return content.split(/\r?\n/)
      .map(line => line.match(rx))
      .filter(match => !!match)
      .map(match => ({
        level: match[1].length,
        caption: match[2],
        slug: toSlug(match[2])
      }));
  }

  levelIndents(level, minLevel) {
    let indents = '';
    for (var i = minLevel; i < level; i++) { indents += '  '; }
    return indents;
  }

  calcTOC(content, lang) {
    const headings = this.headings(content);
    let minLevel = 100; // a max number
    headings.forEach(heading => {
      if (minLevel > heading.level) { minLevel = heading.level; }
    });

    return headings
      .map(heading => (
        this.levelIndents(heading.level, minLevel) + '- ' +
        '[' + this.site.i18n.translate(heading.caption, lang) + ']' +
        '(#' + heading.slug + ')'
      ))
      //.map(heading => `  - [${heading.caption}](#${heading.slug})`)
      .join('\n');
  }

  generateTOC(content, lang) {
    const toc = this.calcTOC(content, lang);
    content = content.replace(TABLE_OF_CONTENTS_TOKEN, toc);
    return content;
  }

  replaceImageLinks(content) {
    return content.replace(/\(\/static\/img\//g, '(' + this.site.url('img/'));
  }

  markdownToHtml(content, lang) {
    content = this.generateTOC(content, lang);
    content = this.replaceImageLinks(content);
    return this.md.render(content);
  }
}

module.exports = Parser;
